<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="urn:net:lin-k:safe-online:payment:4.0"
             xmlns:tns="urn:net:lin-k:safe-online:payment:4.0" name="SafeOnlinePaymentWebService">
    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="urn:net:lin-k:safe-online:payment:4.0" schemaLocation="safe-online-payment-4.0.xsd" />
        </schema>
    </types>

    <!-- =================== Status request ========================= -->

    <message name="statusRequest">
		<part name="request" element="tns:PaymentStatusRequest" />
	</message>
	<message name="statusResponse">
		<part name="response" element="tns:PaymentStatusResponse" />
	</message>

    <!-- =========================== Ports ========================== -->

    <portType name="PaymentServicePort">
		<operation name="status">
			<input message="tns:statusRequest" />
			<output message="tns:statusResponse" />
		</operation>
    </portType>

    <!-- ========================= Bindings ======================== -->

    <binding name="PaymentServiceBinding" type="tns:PaymentServicePort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="status">
            <soap:operation soapAction="urn:net:lin-k:safe-online:payment:4.0:status" />
            <input>
                <soap:body use="literal" />
            </input>
            <output>
                <soap:body use="literal" />
            </output>
        </operation>
    </binding>

    <!-- ========================= Services ======================== -->

    <service name="PaymentService">
        <port name="PaymentServicePort" binding="tns:PaymentServiceBinding">
            <soap:address location="http://localhost:8080/${safe-online.ws.webapp.url}/payment40/" />
        </port>
    </service>
</definitions>
