#! /usr/bin/env bash
# ___________________________________________________________________________ #
#                                                                             #
#       Start -- Stop, Clean-up and Start the Application Server.             #
#                                                                             #
#                                                                             #
#    Licensed under the Apache License, Version 2.0 (the "License");          #
#    you may not use this file except in compliance with the License.         #
#    You may obtain a copy of the License at                                  #
#                                                                             #
#        http://www.apache.org/licenses/LICENSE-2.0                           #
#                                                                             #
#    Unless required by applicable law or agreed to in writing, software      #
#    distributed under the License is distributed on an "AS IS" BASIS,        #
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
#    See the License for the specific language governing permissions and      #
#    limitations under the License.                                           #
# ___________________________________________________________________________ #
#                                                                             #
#                                                                             #
# Copyright 2007, lhunath                                                     #
#   * http://lhunath.lyndir.com                                               #
#   * Maarten Billemont.                                                      #
#                                                                             #
source "${0%/*}/bashlib"                                                      #
scripts="${0%/*}"; [[ $scripts = /* ]] || scripts=$PWD/$scripts
distribution=$(cd "$scripts/.."; echo "${PWD##*/}")
source "$scripts/bashlib"


# Stop the distribution if it's running.
if { kill -0 $(<"$scripts/jboss.pid"); } 2>/dev/null; then
    ask -y!N "This distribution is already running.  Stop it?" || { emit -y "Aborting."; exit 1; }
    "$scripts/stop" || exit
fi


# Delete temporary JBoss stuff.
emit "Cleaning $distribution" --
    rm -rf data/ tmp/ log/ work/
emit -$?


# Initialize the database.
ask -y!N "(Re)Initialize the database?" && { "$scripts/initdb" || exit; }


# Start the distribution.
emit "Starting $distribution" --
    "$scripts/jboss" & # </dev/null >/dev/null 2>&1 &
    sleep 1; kill -0 $! || wait $!
emit -$?
