#! /usr/bin/env bash
# ___________________________________________________________________________ #
#                                                                             #
#       Stop -- Stop the Application Server if it is currently running.       #
#                                                                             #
#                                                                             #
#    Licensed under the Apache License, Version 2.0 (the "License");          #
#    you may not use this file except in compliance with the License.         #
#    You may obtain a copy of the License at                                  #
#                                                                             #
#        http://www.apache.org/licenses/LICENSE-2.0                           #
#                                                                             #
#    Unless required by applicable law or agreed to in writing, software      #
#    distributed under the License is distributed on an "AS IS" BASIS,        #
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
#    See the License for the specific language governing permissions and      #
#    limitations under the License.                                           #
# ___________________________________________________________________________ #
#                                                                             #
#                                                                             #
# Copyright 2007, lhunath                                                     #
#   * http://lhunath.lyndir.com                                               #
#   * Maarten Billemont.                                                      #
#                                                                             #
source "${0%/*}/bashlib"                                                      #
scripts="${0%/*}"; [[ $scripts = /* ]] || scripts=$PWD/$scripts
distribution=$(cd "$scripts/.."; echo "${PWD##*/}")
source "$scripts/bashlib"


# Figure out distribution name from location of script.
cd "$scripts/../jboss/server/default" || { emit -r "Invalid distribution: '$distribution'."; exit 1; }

if [[ -f "$scripts/jboss.pid" && $(<"$scripts/jboss.pid") ]]; then
    emit "Stopping PID $(<"$scripts/jboss.pid")" --
        if ! kill -0 $(<"$scripts/jboss.pid") 2>/dev/null; then
            report "" "Not running."
        else
            kill $(<"$scripts/jboss.pid")
            while kill -0 $(<"$scripts/jboss.pid")
            do sleep 1; done 2>/dev/null
            emit -$? || exit
        fi
fi
