package net.link.safeonline.entity;

public enum HistoryInfoType {
	NONE, CHANGE, ADD, REMOVE, REGISTRATION, PASSWORD_ATTRIBUTE_NOT_FOUND, INCORRECT_PASSWORD, APPLICATION_NOT_FOUND, SUBSCRIPTION_NOT_FOUND, SUCCESS,
}
