<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="urn:net:lin-k:safe-online:idmapping"
	xmlns:tns="urn:net:lin-k:safe-online:idmapping" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
	name="SafeOnlineNameIdentifierMappingWebService">

	<!-- =================== Types =================== -->
	<types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
			<import namespace="urn:oasis:names:tc:SAML:2.0:protocol"
				schemaLocation="saml-schema-protocol-2.0.xsd" />
			<import namespace="urn:net:lin-k:safe-online:idmapping"
				schemaLocation="safe-online-idmapping.xsd" />
		</schema>


	</types>

	<!-- =================== Messages =================== -->

	<message name="LinkIDNameIDMappingRequestMessage">
		<part name="request" element="tns:LinkIDNameIDMappingRequest" />
	</message>
	<message name="NameIDMappingResponseMessage">
		<part name="response" element="samlp:NameIDMappingResponse" />
	</message>

	<!-- =================== Operations =================== -->

	<portType name="NameIdentifierMappingPort">
		<operation name="NameIdentifierMappingQuery">
			<input message="tns:LinkIDNameIDMappingRequestMessage" />
			<output message="tns:NameIDMappingResponseMessage" />
		</operation>
	</portType>

	<!-- =================== Bindings =================== -->

	<binding name="NameIdentifierMappingBinding" type="tns:NameIdentifierMappingPort">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="NameIdentifierMappingQuery">
			<soap:operation soapAction="http://www.oasis-open.org/committees/security" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<!-- =================== Services =================== -->

	<service name="NameIdentifierMappingService">
		<port name="NameIdentifierMappingPort" binding="tns:NameIdentifierMappingBinding">
			<soap:address location="http://localhost:8080/safe-online-ws/idmapping/" />
		</port>
	</service>
</definitions>
