<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="urn:net:lin-k:safe-online:session"
	xmlns:tns="urn:net:lin-k:safe-online:session" name="SafeOnlineSessionTrackingWebService">
	<types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
			<import namespace="urn:net:lin-k:safe-online:session"
				schemaLocation="safe-online-session.xsd" />
		</schema>
	</types>

	<!-- =================== Session Tracking  ======================= -->

	<message name="SessionTrackingRequestMessage">
		<part name="request" element="tns:SessionTrackingRequest"></part>
	</message>
	<message name="SessionTrackingResponseMessage">
		<part name="response" element="tns:SessionTrackingResponse"></part>
	</message>

	<!-- ======================= Authentication Ports =================	-->

	<portType name="SessionTrackingPort">
		<operation name="getAssertions">
			<input message="tns:SessionTrackingRequestMessage" />
			<output message="tns:SessionTrackingResponseMessage" />
		</operation>
	</portType>

	<binding name="SessionTrackingBinding" type="tns:SessionTrackingPort">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="getAssertions">
			<soap:operation soapAction="urn:net:lin-k:safe-online:session:getAssertions" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>

	<service name="SessionTrackingService">
		<port name="SessionTrackingPort" binding="tns:SessionTrackingBinding">
			<soap:address location="http://localhost:8080/safe-online-ws/session/" />
		</port>
	</service>
</definitions>
