/*
 * SafeOnline project.
 * 
 * Copyright 2006-2008 Lin.k N.V. All rights reserved.
 * Lin.k N.V. proprietary/confidential. Use is subject to license terms.
 */
package net.link.safeonline.sdk.auth;

/**
 * <h2>{@link AuthenticationProtocolContext}<br>
 * <sub>[in short] (TODO).</sub></h2>
 * 
 * <p>
 * Authentication Protocol Context class. Objects should be generated by protocol handlers after they have successfully handled an
 * authentication response.
 * </p>
 * 
 * <p>
 * <i>Oct 21, 2008</i>
 * </p>
 * 
 * @author wvdhaute
 */
public class AuthenticationProtocolContext {

    private final String userId;

    private final String authenticatedDevice;


    public AuthenticationProtocolContext(String userId, String authenticatedDevice) {

        this.userId = userId;
        this.authenticatedDevice = authenticatedDevice;
    }

    public String getUserId() {

        return userId;
    }

    public String getAuthenticatedDevice() {

        return authenticatedDevice;
    }

}
