/*
 * SafeOnline project.
 *
 * Copyright 2006-2007 Lin.k N.V. All rights reserved.
 * Lin.k N.V. proprietary/confidential. Use is subject to license terms.
 */
package net.link.safeonline.performance.service;

import java.util.Set;

import javax.ejb.Local;

import net.link.safeonline.performance.DriverException;
import net.link.safeonline.performance.entity.DriverExceptionEntity;
import net.link.safeonline.performance.entity.DriverProfileEntity;
import net.link.safeonline.performance.service.bean.DriverExceptionServiceBean;

/**
 * <h2>{@link DriverExceptionServiceBean}<br>
 * <sub>Service bean for {@link DriverExceptionEntity}.</sub></h2>
 * 
 * <p>
 * Create {@link DriverExceptionEntity}s from {@link DriverException}s
 * </p>
 * <p>
 * <i>Jan 11, 2008</i>
 * </p>
 * 
 * @author mbillemo
 */
@Local
public interface DriverExceptionService {

	public static final String BINDING = "SafeOnline/DriverExceptionService";

	/**
	 * Add the given problem to the database.
	 */
	public DriverExceptionEntity addException(DriverProfileEntity profile,
			DriverException exception);


	/**
	 * Retrieve all {@link DriverExceptionEntity}s that were generated by the
	 * given driver profile.
	 */
	public Set<DriverExceptionEntity> getProfileErrors(
			DriverProfileEntity profile);

}
