/*
 * SafeOnline project.
 *
 * Copyright 2006-2007 Lin.k N.V. All rights reserved.
 * Lin.k N.V. proprietary/confidential. Use is subject to license terms.
 */
package net.link.safeonline.performance.service;

import java.util.List;

import javax.ejb.Local;

import net.link.safeonline.performance.DriverException;
import net.link.safeonline.performance.entity.DriverExceptionEntity;
import net.link.safeonline.performance.entity.DriverProfileEntity;
import net.link.safeonline.performance.service.bean.DriverExceptionServiceBean;


/**
 * <h2>{@link DriverExceptionServiceBean}<br>
 * <sub>Service bean for {@link DriverExceptionEntity}.</sub></h2>
 *
 * <p>
 * Create {@link DriverExceptionEntity}s from {@link DriverException}s
 * </p>
 * <p>
 * <i>Jan 11, 2008</i>
 * </p>
 *
 * @author mbillemo
 */
@Local
public interface DriverExceptionService {

    public static final String BINDING = "SafeOnline/DriverExceptionService";


    /**
     * Add the given problem to the database.
     */
    public DriverExceptionEntity addException(DriverProfileEntity profile, DriverException exception);

    /**
     * Retrieve all {@link DriverExceptionEntity}s that were generated by the given driver profile.<br>
     * <br>
     * The resulting list will be ordered by execution start time.
     */
    public List<DriverExceptionEntity> getAllProfileErrors(DriverProfileEntity profile);

    /**
     * Retrieve {@link DriverExceptionEntity}s that were generated by the given driver profile.<br>
     * <br>
     * The resulting list will be ordered by execution start time.<br>
     * <br>
     * This method will limit the amount of {@link DriverExceptionEntity}s generated to the given amount of data points,
     * possibly averaging out many results inbetween.<br>
     * <br>
     * <b>The resulting entity beans will be detached!</b>
     */
    public List<DriverExceptionEntity> getProfileErrors(DriverProfileEntity profile, int dataPoints);

}
