/*
 * SafeOnline project.
 *
 * Copyright 2006-2007 Lin.k N.V. All rights reserved.
 * Lin.k N.V. proprietary/confidential. Use is subject to license terms.
 */
package net.link.safeonline.performance.service;

import java.util.List;

import javax.ejb.Local;

import net.link.safeonline.performance.entity.DriverProfileEntity;
import net.link.safeonline.performance.entity.ProfileDataEntity;
import net.link.safeonline.performance.entity.ScenarioTimingEntity;
import net.link.safeonline.performance.service.bean.ProfileDataServiceBean;
import net.link.safeonline.util.performance.ProfileData;


/**
 * <h2>{@link ProfileDataServiceBean}<br>
 * <sub>Service bean for {@link ProfileDataEntity}.</sub></h2>
 *
 * <p>
 * Create {@link ProfileDataEntity}s from {@link ProfileData}.
 * </p>
 *
 * <p>
 * <i>Jan 11, 2008</i>
 * </p>
 *
 * @author mbillemo
 */
@Local
public interface ProfileDataService {

    public static final String BINDING = "SafeOnline/ProfileDataService";


    /**
     * Add the given data to the database.
     */
    public ProfileDataEntity addData(DriverProfileEntity profile, ProfileData data, ScenarioTimingEntity agentTime);

    /**
     * Retrieve {@link ProfileDataEntity}s that were generated by the given driver profile.<br>
     * <br>
     * The resulting list will be ordered by execution start time.
     */
    public List<ProfileDataEntity> getAllProfileData(DriverProfileEntity profile);

    /**
     * Retrieve {@link ProfileDataEntity}s that were generated by the given driver profile.<br>
     * <br>
     * The resulting list will be ordered by execution start time.<br>
     * <br>
     * This method will limit the amount of {@link ProfileDataEntity}s generated to the given amount of data points,
     * possibly averaging out many results inbetween.<br>
     * <br>
     * <b>The resulting entity beans will be detached!</b>
     */
    public List<ProfileDataEntity> getProfileData(DriverProfileEntity profile, int dataPoints);
}
