<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	targetNamespace="urn:oasis:names:tc:SAML:2.0:protocol"
	xmlns:tns="urn:oasis:names:tc:SAML:2.0:protocol"
	xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
	name="SafeOnlineAttributeWebService">
	<types>
		<schema xmlns="http://www.w3.org/2001/XMLSchema"
			xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
			<import namespace="urn:oasis:names:tc:SAML:2.0:protocol"
				schemaLocation="saml-schema-protocol-2.0.xsd" />
		</schema>
	</types>
	<message name="AttributeQueryRequestMessage">
		<part name="request" element="samlp:AttributeQuery" />
	</message>
	<message name="AttributeQueryResultMessage">
		<part name="result" element="samlp:Response" />
	</message>
	<portType name="SAMLAttributePort">
		<operation name="AttributeQuery">
			<input message="tns:AttributeQueryRequestMessage" />
			<output message="tns:AttributeQueryResultMessage" />
		</operation>
	</portType>
	<binding name="SAMLAttributeBinding" type="tns:SAMLAttributePort">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<operation name="AttributeQuery">
			<soap:operation
				soapAction="http://www.oasis-open.org/committees/security" />
			<input>
				<soap:body use="literal" />
			</input>
			<output>
				<soap:body use="literal" />
			</output>
		</operation>
	</binding>
	<service name="SAMLAttributeService">
		<port name="SAMLAttributePort"
			binding="tns:SAMLAttributeBinding">
			<soap:address
				location="http://localhost:8080/safe-online-ws/attrib/" />
		</port>
	</service>
</definitions>
