#!/bin/bash
scripts="${0%/*}"; [[ $scripts = /* ]] || scripts=$PWD/$scripts
distribution=$(cd "$scripts/.."; echo "${PWD##*/}")
source "$scripts/bashlib"
shopt -s nullglob

# Parse options.
while [[ $1 = -* ]]; do
    case $1 in
        -L) nolink=1    ;;
        -R) reverse=1   ;;
        -a) apply=1     ;;
        -v) verbose=1   ;;
        -f) force=1     ;;
        *)  break       ;;
    esac

    shift
done


# Parse distribution and base paths.
base="$scripts/.."
work="$base/work"
pwd=$PWD


# Figure out which webapps to use.
webapps=( "$base/jboss/server/default/deploy/"{SafeOnline*,Dodentocht*}.ear )
webapps=( "${webapps[@]%.ear}" )
webapps=( "${webapps[@]##*/}" )
#repos=()
#for webapp in "${webapps[@]}"; do
#    [[ -e "$PWD/${0%/*}/../../$webapp" ]] \
#        && repos+=( "$PWD/${0%/*}/../../$webapp" ) \
#        || repos+=( "$PWD/${0%/*}/.." )
#done
#(( ${#repos[@]} != ${#webapps[@]} )) && {
#    emit -R "Not an equal amount of repositories (${#repos[@]}) and web applications (${#webapps[@]})."
#    exit 1
#}


# Make sure distribution is deployed and files are available for extraction.
(( ! apply )) && {
    tmp=(  )
    [[ -d "$base/jboss/server/default/tmp" ]] || {
        emit -r "Invalid distribution path or distribution not deployed: $distribution at $base"
        exit 1
    }
}


# Extraction work functions.
function extractCss {
    css=( *'/css/style.css' )
    [[ -e $css ]]                                   || return 0

    mkdir -p "$work/$webapp/css"                    || return
    (( reverse )) || {
        mv "$css" "$work/$webapp/css/" && \
        cp "$work/$webapp/css/${css##*/}"{,~}       || return
    }

    for file in "${css[@]}"; do
        if (( nolink )); then
            cp -f "$work/$webapp/css/style.css" "$file"
        else
            ln -f "$work/$webapp/css/style.css" "$file"
        fi

        (( ! $? )) && touch "$file"                 || return
    done
}
function extractHtml {
    while read file; do
        mkdir -p "$work/$webapp/${file%/*}"         || return
        (( reverse )) || {
            mv "$file" "$work/$webapp/$file" && \
            cp "$work/$webapp/$file"{,~}            || return
        }

        [[ -e "$work/$webapp/$file" ]] && {
            if (( nolink )); then
                cp -f "$work/$webapp/$file" "$file"
            else
                ln -f "$work/$webapp/$file" "$file"
            fi

            (( ! $? )) || return
        }

        touch "$file"                               || return
    done < <(find . -name '*.xhtml' -o -name '*.html')
}
function extractStuff {

        extractCss && \
        extractHtml
}


# Figure out what to do now.
if (( apply )); then
    [[ ! -e $work ]] && {
        emit -R "No work files present at $(shorten "$work").  Cannot apply."
        exit 1
    }
elif (( ! reverse )); then
    [[ -e $work ]] && {
        emit -Y "You already have work files at $(shorten "$work").  Perhaps you meant to use -R?"
        emit -Y "Continuing will delete all these files and replace them by the current server's files."
        echo; ask -y!N "Continue?" || exit

        emit "Cleaning up $(shorten "$work")" --
            rm -rf "$work"
        emit -$?
    }
fi

if (( reverse )); then
    emit "Linking web files from $(shorten "$work") to $(shorten "$base")" --
elif (( apply )); then
    emit "Applying web files from $(shorten "$work") to repository" --
else
    emit "Linking web files from $(shorten "$base") to $(shorten "$work")" --
fi

if (( apply )); then
    for w in "${!webapps[@]}"; do
        webapp=${webapps[w]}
        cd "$work/$webapp"

        find . '(' -name '*.xhtml' -o -name '*.css' ')' -print0 | while read -d '' file; do
            [[ -e $file~ ]] || {
                emit -y "Backup of $(shorten -p "$pwd" "$file") not found."
                continue
            }

            if (( force )) || [[ $(openssl md4 < "$file") != $(openssl md4 < "$file~") ]]; then
                ddest="${repos[w]}/${file/-1.0-SNAPSHOT-exp.war//src/main/webapp}"

                if ! [[ -e $ddest ]]; then
                    adest=( "${repos[w]}/"*"/src/main/webapp/${file/*-1.0-SNAPSHOT-exp.war/}" )
                    for ad in ${!adest[@]}; do
                        for exclude in $excludes; do
                            [[ ${adest[ad]} = *$exclude* ]] && unset adest[ad]
                        done
                    done
                    adest=("${adest[@]}")

                    if (( ! ${#adest[@]} || ${#adest[@]} > 1 )) || [[ ! -e $adest ]]; then
                        emit -y "Source of $(shorten -p "$pwd" "$file") not found.  Tried:"
                        for dest in "$ddest" "${adest[@]}"; do
                            emit -y "   - $(shorten -p "$pwd" "$dest"):"\
                                    "$([[ -e $dest ]] && echo "${green}exists${reset}." || echo "${red}doesn't exist${reset}.")"
                        done

                        continue
                    fi

                    dest=$adest
                else
                    dest=$ddest
                fi

                (( verbose )) && {
                    emit "Modifying $(shorten -p "$pwd" "$dest")"
                    emit "   - Source: $(shorten -p "$pwd" "$file")."
                }
                mv "$dest"{,~} && cp "$file" "$dest"
            fi
        done
    done
else
    for webapp in "${webapps[@]}"; do
        loc=( "$base"/jboss/server/default/tmp/deploy/*"$webapp.ear-contents"/*/META-INF/../.. )
        (( ${#loc[@]} )) && cd "$loc" && \
            extractStuff
    done
fi

emit -$?
