#!/bin/bash
source "${0%/*}"/bashlib


# Parse options.
while [[ $1 = -* ]]; do
    case $1 in
        -L) nolink=1    ;;
        -R) reverse=1   ;;
        -a) apply=1     ;;
        -v) verbose=1   ;;
        -f) force=1     ;;
        *)  break       ;;
    esac

    shift
done


# Parse distribution and base paths.
(( ! apply )) && { distribution=$1; shift; }
base="${1:-${0%/*}/..}"; shift
pwd=$PWD


# Figure out which webapps to use.
(( $# )) && \
    webapps=("$@") || \
    webapps=( SafeOnline{,Beid,Demo,Digipass,Encap} )
(( ! ${#repos[@]} )) && {
    repos=()
    for webapp in "${webapps[@]}"; do
        [[ -e "$PWD/${0%/*}/../../$webapp" ]] \
            && repos+=( "$PWD/${0%/*}/../../$webapp" ) \
            || repos+=( "$PWD/${0%/*}/.." )
    done
}
(( ${#repos[@]} != ${#webapps[@]} )) && {
    emit -R "Not an equal amount of repositories (${#repos[@]}) and web applications (${#webapps[@]})."
    exit 1
}


# Figure out path to distribution.
(( ! apply )) && {
    [[ ! $distribution ]] && {
        distribution=$(cd "$base/safe-online-base-distribution/target/"*"/jboss/server/default/deploy/../../../../"; echo "$PWD")
    }

    [[ ! -d $distribution/jboss/server/default/tmp ]] && {
        emit -r "Invalid distribution path or distribution not deployed: '$distribution'"
        exit 1
    }
}
base="$base/work"


# Make paths absolute.
[[ -x $(type -P readlink 2>/dev/null) ]] && {
    base=$(readlink -m "$base")
    distribution=$(readlink -m "$distribution")
}
[[ $base = /* ]] || base="$PWD/$base"


# Extraction work functions.
function extractCss {
    css=( *'/css/style.css' )
    [[ -e $css ]]                                   || return 0

    mkdir -p "$base/$webapp/css"                    || return
    (( reverse )) || {
        mv "$css" "$base/$webapp/css/" && \
        cp "$base/$webapp/css/${css##*/}"{,~}       || return
    }

    for file in "${css[@]}"; do
        if (( nolink )); then
            cp -f "$base/$webapp/css/style.css" "$file"
        else
            ln -f "$base/$webapp/css/style.css" "$file"
        fi

        (( ! $? )) && touch "$file"                 || return
    done
}
function extractHtml {
    while read file; do
        mkdir -p "$base/$webapp/${file%/*}"         || return
        (( reverse )) || {
            mv "$file" "$base/$webapp/$file" && \
            cp "$base/$webapp/$file"{,~}            || return
        }

        [[ -e "$base/$webapp/$file" ]] && {
            if (( nolink )); then
                cp -f "$base/$webapp/$file" "$file"
            else
                ln -f "$base/$webapp/$file" "$file"
            fi

            (( ! $? )) || return
        }

        touch "$file"                               || return
    done < <(find . -name '*.xhtml' -o -name '*.html')
}
function extractStuff {

        extractCss && \
        extractHtml
}


# Figure out what to do now.
if (( apply )); then
    [[ ! -e $base ]] && {
        emit -R "No work files present at '$(shorten "$base")'.  Cannot apply."
        exit 1
    }
elif (( ! reverse )); then
    [[ -e $base ]] && {
        emit -Y "You already have work files at '$(shorten "$base")'.  Perhaps you meant to use -R?"
        emit -Y "Continuing will delete all these files and replace them by the current server's files."
        echo; ask -y!N "Continue?" || exit
    }

    emit "Cleaning up '$base'" --
        rm -rf "$base"
    emit -$?
fi

if (( reverse )); then
    emit "Linking CSS and XHTML files from '$(shorten "$base")' to '$(shorten "$distribution")'" --
elif (( apply )); then
    emit "Applying CSS and XHTML files from '$(shorten "$base")' to repository" --
else
    emit "Linking CSS and XHTML files from '$(shorten "$distribution")' to '$(shorten "$base")'" --
fi

if (( apply )); then
    for w in "${!webapps[@]}"; do
        webapp=${webapps[w]}
        cd "$base/$webapp"

        find . '(' -name '*.xhtml' -o -name '*.css' ')' -print0 | while read -d '' file; do
            [[ -e $file~ ]] || {
                emit -y "Backup of '$(shorten -p "$pwd" "$file")' not found."
                continue
            }

            if (( force )) || [[ $(openssl md4 < "$file") != $(openssl md4 < "$file~") ]]; then
                ddest="${repos[w]}/${file/-1.0-SNAPSHOT-exp.war//src/main/webapp}"

                if ! [[ -e $ddest ]]; then
                    adest=( "${repos[w]}/"*"/src/main/webapp/${file/*-1.0-SNAPSHOT-exp.war/}" )
                    for ad in ${!adest[@]}; do
                        for exclude in $excludes; do
                            [[ ${adest[ad]} = *$exclude* ]] && unset adest[ad]
                        done
                    done
                    adest=("${adest[@]}")

                    if (( ! ${#adest[@]} || ${#adest[@]} > 1 )) || [[ ! -e $adest ]]; then
                        emit -y "Source of '$(shorten -p "$pwd" "$file")' not found.  Tried:"
                        for dest in "$ddest" "${adest[@]}"; do
                            emit -y "   - $(shorten -p "$pwd" "$dest"):"\
                                    "$([[ -e $dest ]] && echo "${green}exists${reset}." || echo "${red}doesn't exist${reset}.")"
                        done

                        continue
                    fi

                    dest=$adest
                else
                    dest=$ddest
                fi

                (( verbose )) && {
                    emit "Modifying $(shorten -p "$pwd" "$dest")"
                    emit "   - Source: $(shorten -p "$pwd" "$file")."
                }
                mv "$dest"{,~} && cp "$file" "$dest"
            fi
        done
    done
else
    for webapp in "${webapps[@]}"; do
        cd "$distribution/jboss/server/default/tmp/deploy/"*"$webapp.ear-contents/"*"/META-INF/../.." && \
            extractStuff
    done
fi

emit -$?
