#!/bin/bash
source "${0%/*}/bashlib"                                                      #
nonGnuSed=$(sed -i '' /dev/null >/dev/null 2>&1; [[ $? != 4 ]] && echo 1)

cd "$(readlink -f "${0%/*}/..")"

p=${PWD##*/}
emit "Converting JAR dependencies on safe-online projects to source dependencies" --
    sed -i ${nonGnuSed:+''} '/M2_REPO.*\/'"$p"'\// { s,M2_REPO/net/lin-k/'"$p"'/\([^/]*\)/[^"]*,/\1,; s/kind="var"/kind="src"/; }' */.classpath
emit -$?

emit "Converting EJB2 eclipse projects into EJB3" --
    for p in !(scripts)/.settings/org.eclipse.wst.common.component; do
        cp scripts/org.eclipse.wst.common.* "${p%/*}" \
            && sed -i ${nonGnuSed:+''} 's/safe-online-projectname/'"${p%%/*}"'/' "$p" \
                || break
    done
emit -$?
