#!/bin/bash
source "${0%/*}/bashlib"                                                      #
nonGnuSed=$(sed -i '' /dev/null >/dev/null 2>&1; [[ $? != 4 ]] && echo 1)

cd "$(readlink -f "${0%/*}/..")"

p=${PWD##*/}
emit "Converting JAR dependencies on safe-online projects to source dependencies" --
    sed -i ${nonGnuSed:+''} '/M2_REPO.*\/'"$p"'\// { s,M2_REPO/net/lin-k/'"$p"'/\([^/]*\)/[^"]*,/\1,; s/kind="var"/kind="src"/; }' */.classpath
emit -$?

emit "Converting EJB2 eclipse projects into EJB3" --
    for p in */.settings; do
        cp scripts/org.eclipse.* "$p" \
        && sed -i ${nonGnuSved:+''} 's/safe-online-projectname/'"${p%%/*}"'/' "$p/org.eclipse.wst.common.component" \
        || break

        # Special configuration for -ws projects (eg: other warning config for generated sources).
        [[ ${p%%/*} != *-ws ]] || {
            for f in scripts/ws~org.eclipse.*; do
                cp "$f" "$p/${f#'scripts/ws~'}" || break 2
            done
        }
    done
emit -$?
