#!/bin/bash

emit "Extracting archives recursively" --
    mkdir -p "$workdir/"{old,new}

    cd "$workdir/old" && unzip -qq "$old" || \
        { emit -$?; exit $?; }
    cd "$workdir/new" && unzip -qq "$new" || \
        { emit -$?; exit $?; }

    keepDigging=1
    for (( i=0; keepDigging; ++i )); do
        emit "Starting level $i"
        for d in old new; do
            cd "$workdir/$d"
            if (( i )); then
                keepDigging=0
                while read -d ''; do
                    cd "$REPLY"

                    extractAll || \
                        { emit -$?; exit $?; }

                    keepDigging=1
                done < <(find "$PWD" -mindepth $i -maxdepth $i -type d -name '_*.?ar' -print0)
            else
                extractAll
            fi
        done
    done
emit -0

