#!/bin/bash
source "${0%/*}/bashlib"                                                      #
nonGnuSed=$(sed -i '' /dev/null >/dev/null 2>&1; [[ $? != 4 ]] && echo 1)

cd "${0%/*}/.."

p=${PWD##*/}
emit "Converting JAR dependencies on safe-online projects to source dependencies" --
    sed -i ${nonGnuSed:+''} '/-client/ ! { /M2_REPO.*\/'"$p"'\// { s,M2_REPO/net/lin-k/'"$p"'/\([^/]*\)/[^"]*,/\1,; s/kind="var"/kind="src"/; } }' */.classpath
    for pp in */.classpath; do
        IFS=$'\n' srcs=($(grep -F 'kind="src"' "$pp" | cut -d'"' -f4)); unset IFS
        while read -r; do
            line=$REPLY

            if [[ $line = *'-client'* ]]; then
                curSrc=$(sed '/'"$p"'/ { s,.*M2_REPO/net/lin-k/'"$p"'/\([^/]*\)/.*,/\1, }' <<< "$line")
                for src in "${srcs[@]}"; do
                    [[ $src = $curSrc ]] && continue 2
                done

                line=$(sed '/'"$p"'/ { s,M2_REPO/net/lin-k/'"$p"'/\([^/]*\)/[^"]*,/\1,; s/kind="var"/kind="src"/ }' <<< "$line")
            fi

            echo "$line"
        done <<< "$(<"$pp")" > "$pp~"
        mv -f "$pp~" "$pp"
    done
emit -$?

emit -o "Setting up project-specific configurations" --
    echo -n "$save"

    result=0
    for p in */.settings; do
        echo -n "$load${p%/*} ..$eel"

        cp scripts/org.eclipse.jdt.* "$p" \
            || { result=$?; break; }

        # Special configuration for projects with generated sources.
        [[ -e ${p%%/*}/target/generated-sources ]] && {
            for f in scripts/ws~org.eclipse.*; do
                cp "$f" "$p/${f#'scripts/ws~'}" || { result=$?; break 2; }
            done
        }
    done

    echo
emit -$result
