#!/bin/bash
# ___________________________________________________________________________ #
#                                                                             #
#       Mvn2Eclipse -- Prepare Maven2 Artifacts for use in Eclipse.           #
#                                                                             #
#                                                                             #
#    Licensed under the Apache License, Version 2.0 (the "License");          #
#    you may not use this file except in compliance with the License.         #
#    You may obtain a copy of the License at                                  #
#                                                                             #
#        http://www.apache.org/licenses/LICENSE-2.0                           #
#                                                                             #
#    Unless required by applicable law or agreed to in writing, software      #
#    distributed under the License is distributed on an "AS IS" BASIS,        #
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
#    See the License for the specific language governing permissions and      #
#    limitations under the License.                                           #
# ___________________________________________________________________________ #
#                                                                             #
#                                                                             #
# Copyright 2007, lhunath                                                     #
#   * http://lhunath.lyndir.com                                               #
#   * Maarten Billemont.                                                      #
#                                                                             #
source "${0%/*}/bashlib"                                                      #
cd "${0%/*}/.."


# Setup and parse arguments.
noMaven=
offline=
nonGnuSed=$(sed -i '' /dev/null >/dev/null 2>&1; [[ $? != 4 ]] && echo 1)
for arg in $(getArgs oM "$@"); do
    case $arg in
        M) noMaven=1    ;;
        o) offline=1    ;;
    esac
done


# Run the maven2 eclipse plugin.
if (( ! noMaven )); then
    mvn ${offline:+-o} eclipse:eclipse \
        || report "Maven eclipse plugin failed." || exit
fi


# Convert any JAR references of projects into source references.
p=${PWD##*/}
emit "Converting JAR dependencies on safe-online projects to source dependencies" --
    sed -i ${nonGnuSed:+''} '/-client/ ! { /M2_REPO.*\/'"$p"'\// { s,M2_REPO/net/lin-k/'"$p"'/\([^/]*\)/[^"]*,/\1,; s/kind="var"/kind="src"/; } }' */.classpath
    for pp in */.classpath; do
        IFS=$'\n' srcs=($(grep -F 'kind="src"' "$pp" | cut -d'"' -f4)); unset IFS
        while read -r; do
            line=$REPLY

            if [[ $line = *'-client'* ]]; then
                curSrc=$(sed '/'"$p"'/ { s,.*M2_REPO/net/lin-k/'"$p"'/\([^/]*\)/.*,/\1, }' <<< "$line")
                for src in "${srcs[@]}"; do
                    [[ $src = $curSrc ]] && continue 2
                done

                line=$(sed '/'"$p"'/ { s,M2_REPO/net/lin-k/'"$p"'/\([^/]*\)/[^"]*,/\1,; s/kind="var"/kind="src"/ }' <<< "$line")
            fi

            echo "$line"
        done <<< "$(<"$pp")" > "$pp~"
        mv -f "$pp~" "$pp"
    done
emit -$?


# Setup project-specific configurations such as Formatter, Clean-up, Compiler Errors and Warnings, etc.
emit -o "Setting up project-specific configurations" --
    echo -n "$save"

    result=0
    for p in */.settings; do
        echo -n "$load${p%/*} ..$eel"

        cp scripts/org.eclipse.jdt.* "$p" \
            || { result=$?; break; }

        # Special configuration for projects with generated sources.
        [[ -e ${p%%/*}/target/generated-sources ]] && {
            for f in scripts/ws~org.eclipse.*; do
                cp "$f" "$p/${f#'scripts/ws~'}" || { result=$?; break 2; }
            done
        }
    done

    echo
emit -$result
