/*
 * SafeOnline project.
 * 
 * Copyright 2006-2007 Lin.k N.V. All rights reserved.
 * Lin.k N.V. proprietary/confidential. Use is subject to license terms.
 */

package net.link.safeonline.auth.protocol;

/**
 * Protocol Context class. Protocol Context objects should be generated by
 * protocol handlers after they have successfully processed an authentication
 * request.
 * 
 * @author fcorneli
 * 
 */
public class ProtocolContext {

	private final String applicationId;

	private final String target;

	/**
	 * Main constructor.
	 * 
	 * @param applicationId
	 *            the application Id of the application that the authentication
	 *            protocol handler has determined that issued the authentication
	 *            request.
	 * @param target
	 *            the target URL to which to send the authentication response.
	 */
	public ProtocolContext(String applicationId, String target) {
		this.applicationId = applicationId;
		this.target = target;
	}

	public String getApplicationId() {
		return this.applicationId;
	}

	public String getTarget() {
		return this.target;
	}
}
